export const MOCK_PROPERTIES = [
  // ==========================================
  // HYDERABAD & SECUNDERABAD PROPERTIES (Real)
  // ==========================================
  {
    _id: "hp1",
    id: "hp1",
    title: "Vrr Homes Land Dammaiguda",
    description: "Premium open residential plot in VRR Homes layout, Dammaiguda. Clear title, gated community boundary wall, and immediately ready for independent house construction.",
    listingType: "sale",
    price: 5500000,
    location: "Dammaiguda, Secunderabad",
    city: "Hyderabad",
    locality: "Dammaiguda",
    coordinates: { lat: 17.4912, lng: 78.5834 },
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 0,
    bathrooms: 0,
    areaSqft: 1800,
    area: "1800 sqft",
    category: "plot",
    verified: true,
    featured: true,
    furnishing: "unfurnished",
    parking: 0,
    amenities: ["Security", "Gated Boundary", "Rainwater Harvesting"],
    advertiserType: "owner",
    createdAt: new Date().toISOString()
  },
  {
    _id: "hp2",
    id: "hp2",
    title: "2 BHK Independent House/Villa in Dammaiguda",
    description: "Sleek 2 BHK Independent House in Dammaiguda, Secunderabad. Beautiful hall, spacious rooms, independent borewell, and modular kitchen fittings.",
    listingType: "sale",
    price: 5800000,
    location: "Dammaiguda, Secunderabad",
    city: "Hyderabad",
    locality: "Dammaiguda",
    coordinates: { lat: 17.4930, lng: 78.5815 },
    image: "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1250,
    area: "1250 sqft",
    category: "independent-house",
    verified: true,
    featured: false,
    furnishing: "semi-furnished",
    parking: 1,
    amenities: ["Power Backup", "Parking", "Security"],
    advertiserType: "owner",
    createdAt: new Date().toISOString()
  },
  {
    _id: "hp3",
    id: "hp3",
    title: "VRR Green Park Enclave Plot",
    description: "Beautiful residential land plot in VRR Green Park Enclave, Dammaiguda. Prime locality with high appreciation potential, ready for registration.",
    listingType: "sale",
    price: 5700000,
    location: "Dammaiguda, Secunderabad",
    city: "Hyderabad",
    locality: "Dammaiguda",
    coordinates: { lat: 17.4905, lng: 78.5840 },
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 0,
    bathrooms: 0,
    areaSqft: 2000,
    area: "2000 sqft",
    category: "plot",
    verified: true,
    featured: true,
    furnishing: "unfurnished",
    parking: 0,
    amenities: ["Gated Boundary", "Rainwater Harvesting"],
    advertiserType: "owner",
    createdAt: new Date().toISOString()
  },
  {
    _id: "hp4",
    id: "hp4",
    title: "2 BHK House in Sunshine Colony Dammaiguda",
    description: "Spacious independent house located at Sunshine Colony Road No 3, Dammaiguda. Double bedrooms, modern structure, Municipal drinking water line, and parking space.",
    listingType: "sale",
    price: 6000000,
    location: "Dammaiguda, Secunderabad",
    city: "Hyderabad",
    locality: "Dammaiguda",
    coordinates: { lat: 17.4950, lng: 78.5870 },
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1400,
    area: "1400 sqft",
    category: "independent-house",
    verified: false,
    featured: false,
    furnishing: "unfurnished",
    parking: 1,
    amenities: ["Parking", "Water Tank", "Security"],
    advertiserType: "owner",
    createdAt: new Date().toISOString()
  },
  {
    _id: "hp5",
    id: "hp5",
    title: "4 BHK Independent House in ECIL Cherlapally",
    description: "Spacious independent duplex house with 4 bedrooms, 3 bathrooms in INDEPENDENT HOUSE KUSAIGUDA, ECIL. Peaceful colony with great connectivity.",
    listingType: "sale",
    price: 5800000,
    location: "ECIL, Cherlapally, Secunderabad",
    city: "Hyderabad",
    locality: "ECIL",
    coordinates: { lat: 17.4720, lng: 78.5720 },
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 4,
    bathrooms: 3,
    areaSqft: 2100,
    area: "2100 sqft",
    category: "independent-house",
    verified: true,
    featured: true,
    furnishing: "semi-furnished",
    parking: 2,
    amenities: ["Power Backup", "Parking", "Garden"],
    advertiserType: "owner",
    createdAt: new Date().toISOString()
  },
  {
    _id: "hp6",
    id: "hp6",
    title: "2 BHK VRR Enclave House Dammaiguda",
    description: "Fully completed 2 BHK Independent house/villa in VRR Enclave, Dammaiguda. Ready to move, gated layout, perfect ventilation.",
    listingType: "sale",
    price: 6500000,
    location: "Dammaiguda, Secunderabad",
    city: "Hyderabad",
    locality: "Dammaiguda",
    coordinates: { lat: 17.4925, lng: 78.5830 },
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1300,
    area: "1300 sqft",
    category: "independent-house",
    verified: true,
    featured: true,
    furnishing: "semi-furnished",
    parking: 1,
    amenities: ["Gated Boundary", "Security", "Parking"],
    advertiserType: "owner",
    createdAt: new Date().toISOString()
  },
  {
    _id: "hp7",
    id: "hp7",
    title: "2 BHK House in Elephant Enclave Rampally",
    description: "Premium independent 2 BHK house in Elephant Enclave, Rampally. Close to Outer Ring Road, high appreciation locality.",
    listingType: "sale",
    price: 4975000,
    location: "Rampally, Secunderabad",
    city: "Hyderabad",
    locality: "Rampally",
    coordinates: { lat: 17.4850, lng: 78.6180 },
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1150,
    area: "1150 sqft",
    category: "independent-house",
    verified: true,
    featured: false,
    furnishing: "unfurnished",
    parking: 1,
    amenities: ["Security", "Parking", "Water Tank"],
    advertiserType: "dealer",
    createdAt: new Date().toISOString()
  },
  {
    _id: "hp8",
    id: "hp8",
    title: "2 BHK Independent Villa in ECIL",
    description: "Sleek independent villa with 2 bedrooms, 2 bathrooms in ECIL. Brand new build, low maintenance, parking, and municipal water line.",
    listingType: "sale",
    price: 5200000,
    location: "ECIL, Cherlapally, Secunderabad",
    city: "Hyderabad",
    locality: "ECIL",
    coordinates: { lat: 17.4710, lng: 78.5710 },
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1200,
    area: "1200 sqft",
    category: "independent-house",
    verified: true,
    featured: false,
    furnishing: "semi-furnished",
    parking: 1,
    amenities: ["Parking", "Water Storage", "Security"],
    advertiserType: "dealer",
    createdAt: new Date().toISOString()
  },
  {
    _id: "hp9",
    id: "hp9",
    title: "Plot for Sale in Rampally",
    description: "HUDA approved layout open residential plot in Rampally, Secunderabad. Perfect size and pricing, quick registration.",
    listingType: "sale",
    price: 4500000,
    location: "Rampally, Secunderabad",
    city: "Hyderabad",
    locality: "Rampally",
    coordinates: { lat: 17.4870, lng: 78.6190 },
    image: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 0,
    bathrooms: 0,
    areaSqft: 1800,
    area: "1800 sqft",
    category: "plot",
    verified: true,
    featured: false,
    furnishing: "unfurnished",
    parking: 0,
    amenities: ["Gated Boundary"],
    advertiserType: "owner",
    createdAt: new Date().toISOString()
  },

  // ------------------------------------------
  // HYDERABAD PROJECTS & HIGH DEMAND APARTMENTS
  // ------------------------------------------
  {
    _id: "hp_p1",
    id: "hp_p1",
    title: "Harika VK Grand Apartment",
    description: "RERA registered 2 & 3 BHK premium apartment project in Nagole, Hyderabad. Excellent construction quality and luxury modern living amenities.",
    listingType: "sale",
    price: 8200000,
    location: "Nagole, Hyderabad",
    city: "Hyderabad",
    locality: "Nagole",
    coordinates: { lat: 17.3820, lng: 78.5640 },
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 1550,
    area: "1550 sqft",
    category: "apartment",
    verified: true,
    featured: true,
    furnishing: "unfurnished",
    parking: 1,
    amenities: ["Lift", "Gym", "Power Backup", "Security", "Club House"],
    reraId: "RERA-HYD-5021",
    advertiserType: "builder",
    createdAt: new Date().toISOString()
  },
  {
    _id: "hp_p2",
    id: "hp_p2",
    title: "Krishna Bai Residency Uppal",
    description: "Ready-to-move 2 & 3 BHK flats in Krishna Bai Residency, Uppal. Features wide corridors, premium fittings, high-quality structure, and close to Uppal Metro.",
    listingType: "sale",
    price: 7400000,
    location: "Uppal, Hyderabad",
    city: "Hyderabad",
    locality: "Uppal",
    coordinates: { lat: 17.4010, lng: 78.5600 },
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1250,
    area: "1250 sqft",
    category: "apartment",
    verified: true,
    featured: true,
    furnishing: "semi-furnished",
    parking: 1,
    amenities: ["Lift", "Power Backup", "Parking", "Security"],
    reraId: "RERA-HYD-1190",
    advertiserType: "builder",
    createdAt: new Date().toISOString()
  },
  {
    _id: "hp_p3",
    id: "hp_p3",
    title: "Anuhar Gautami Heights Miyapur",
    description: "Possession from Dec 2026. 2 & 3 BHK Luxury Apartment in Anuhar Gautami Heights, Miyapur. World class amenities including double swimming pool and organic garden.",
    listingType: "sale",
    price: 9800000,
    location: "Miyapur, Hyderabad",
    city: "Hyderabad",
    locality: "Miyapur",
    coordinates: { lat: 17.4980, lng: 78.3490 },
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 1750,
    area: "1750 sqft",
    category: "apartment",
    verified: true,
    featured: true,
    furnishing: "unfurnished",
    parking: 2,
    amenities: ["Swimming Pool", "Gym", "Power Backup", "Security", "Children Play Area"],
    reraId: "RERA-HYD-9988",
    advertiserType: "builder",
    createdAt: new Date().toISOString()
  },
  {
    _id: "hp_p4",
    id: "hp_p4",
    title: "Candeur Crescent Gachibowli",
    description: "Ready To Move high rise luxury project Candeur Crescent, Gachibowli. 3 BHK premium apartment flat overlooking Gachibowli skyline.",
    listingType: "sale",
    price: 19500000,
    location: "Gachibowli, Hyderabad",
    city: "Hyderabad",
    locality: "Gachibowli",
    coordinates: { lat: 17.4410, lng: 78.3470 },
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 2200,
    area: "2200 sqft",
    category: "apartment",
    verified: true,
    featured: true,
    furnishing: "fully-furnished",
    parking: 2,
    amenities: ["Swimming Pool", "Gym", "Club House", "Power Backup", "Security"],
    reraId: "RERA-HYD-4455",
    advertiserType: "builder",
    createdAt: new Date().toISOString()
  },
  {
    _id: "hp_p5",
    id: "hp_p5",
    title: "Bricks Marvella Tellapur",
    description: "Possession from Jan 2028. Bricks Marvella, Tellapur, Hyderabad. 3 & 4 BHK ultra premium apartment flats. High-class construction and world-class landscaping.",
    listingType: "sale",
    price: 16000000,
    location: "Tellapur, Hyderabad",
    city: "Hyderabad",
    locality: "Tellapur",
    coordinates: { lat: 17.4580, lng: 78.2910 },
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 1850,
    area: "1850 sqft",
    category: "apartment",
    verified: true,
    featured: true,
    furnishing: "unfurnished",
    parking: 2,
    amenities: ["Swimming Pool", "Gym", "Club House", "Power Backup", "Security", "CCTV"],
    reraId: "RERA-HYD-7788",
    advertiserType: "builder",
    createdAt: new Date().toISOString()
  },

  // ==========================================
  // VISAKHAPATNAM (VIZAG) PROPERTIES
  // ==========================================
  {
    _id: "vp1",
    id: "vp1",
    title: "Premium 3 BHK Apartment in Madhurawada",
    description: "Sleek modern 3 BHK flat with luxury amenities in Madhurawada, Visakhapatnam. Close to IT Hill and beaches.",
    listingType: "sale",
    price: 6500000,
    location: "Madhurawada, Visakhapatnam",
    city: "Visakhapatnam",
    locality: "Madhurawada",
    coordinates: { lat: 17.8185, lng: 83.3485 },
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 1650,
    area: "1650 sqft",
    category: "apartment",
    verified: true,
    featured: true,
    furnishing: "semi-furnished",
    parking: 1,
    amenities: ["Power Backup", "Gym", "Security", "Parking"],
    reraId: "RERA-901234",
    advertiserType: "builder",
    createdAt: new Date().toISOString()
  },
  {
    _id: "vp2",
    id: "vp2",
    title: "Luxury 4 BHK Villa in Yendada",
    description: "Gated luxury 4 BHK villa with ocean breeze in Yendada, Visakhapatnam. Beautiful sea views and private lawn.",
    listingType: "sale",
    price: 18500000,
    location: "Yendada, Visakhapatnam",
    city: "Visakhapatnam",
    locality: "Yendada",
    coordinates: { lat: 17.7850, lng: 83.3610 },
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 4,
    bathrooms: 4,
    areaSqft: 3200,
    area: "3200 sqft",
    category: "villa",
    verified: true,
    featured: true,
    furnishing: "fully-furnished",
    parking: 2,
    amenities: ["Swimming Pool", "Gym", "Club House", "Security", "Garden"],
    reraId: "RERA-456789",
    advertiserType: "owner",
    createdAt: new Date().toISOString()
  },
  {
    _id: "vp3",
    id: "vp3",
    title: "Spacious 2 BHK Builder Floor in Seethammadhara",
    description: "Ready-to-move-in independent builder floor at Seethammadhara. Prime residential area with municipal water connection.",
    listingType: "sale",
    price: 4800000,
    location: "Seethammadhara, Visakhapatnam",
    city: "Visakhapatnam",
    locality: "Seethammadhara",
    coordinates: { lat: 17.7410, lng: 83.3120 },
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1100,
    area: "1100 sqft",
    category: "builder-floor",
    verified: true,
    featured: false,
    furnishing: "semi-furnished",
    parking: 1,
    amenities: ["Lift", "Security", "Parking"],
    advertiserType: "dealer",
    createdAt: new Date().toISOString()
  },

  // ==========================================
  // SRIKAKULAM PROPERTIES
  // ==========================================
  {
    _id: "sp1",
    id: "sp1",
    title: "Independent House in Balaga Srikakulam",
    description: "Beautiful independent house with ground and first floor in Balaga. Located in a quiet locality with friendly neighbors.",
    listingType: "sale",
    price: 5200000,
    location: "Balaga, Srikakulam",
    city: "Srikakulam",
    locality: "Balaga",
    coordinates: { lat: 18.3012, lng: 83.8990 },
    image: "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 1800,
    area: "1800 sqft",
    category: "independent-house",
    verified: true,
    featured: true,
    furnishing: "semi-furnished",
    parking: 1,
    amenities: ["Power Backup", "Parking", "Water Tank"],
    advertiserType: "owner",
    createdAt: new Date().toISOString()
  },
  {
    _id: "sp2",
    id: "sp2",
    title: "Venture Plots in Etcherla near Highway",
    description: "HMDA standard open plots in Etcherla, close to Dr. B.R. Ambedkar University. Clear title, spot registration, and fast-developing venture.",
    listingType: "sale",
    price: 1800000,
    location: "Etcherla, Srikakulam",
    city: "Srikakulam",
    locality: "Etcherla",
    coordinates: { lat: 18.2720, lng: 83.8340 },
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 0,
    bathrooms: 0,
    areaSqft: 1500,
    area: "1500 sqft",
    category: "plot",
    verified: true,
    featured: false,
    furnishing: "unfurnished",
    parking: 0,
    amenities: ["Security", "Rainwater Harvesting"],
    advertiserType: "dealer",
    createdAt: new Date().toISOString()
  },

  // ==========================================
  // BANGALORE PROPERTIES
  // ==========================================
  {
    _id: "bp1",
    id: "bp1",
    title: "Gated Community Villa in Whitefield",
    description: "Modern architectural masterpiece 4 BHK villa with high ceilings, private pool deck, and beautiful landscapes in Whitefield Bangalore.",
    listingType: "sale",
    price: 26000000,
    location: "Whitefield, Bangalore",
    city: "Bangalore",
    locality: "Whitefield",
    coordinates: { lat: 12.9698, lng: 77.7500 },
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 4,
    bathrooms: 5,
    areaSqft: 3600,
    area: "3600 sqft",
    category: "villa",
    verified: true,
    featured: true,
    furnishing: "fully-furnished",
    parking: 2,
    amenities: ["Swimming Pool", "Gym", "Club House", "Security", "Garden"],
    reraId: "RERA-112233",
    advertiserType: "builder",
    createdAt: new Date().toISOString()
  },
  {
    _id: "bp2",
    id: "bp2",
    title: "3 BHK Apartment for Rent in HSR Layout",
    description: "Fully furnished high-end 3 BHK apartment with modern interior woodwork. Close to cafes, parks, and startup offices in HSR Layout.",
    listingType: "rent",
    price: 55000,
    location: "HSR Layout, Bangalore",
    city: "Bangalore",
    locality: "HSR Layout",
    coordinates: { lat: 12.9116, lng: 77.6446 },
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 1800,
    area: "1800 sqft",
    category: "apartment",
    verified: true,
    featured: false,
    furnishing: "fully-furnished",
    parking: 1,
    amenities: ["Gym", "Security", "Power Backup", "Parking"],
    advertiserType: "dealer",
    createdAt: new Date().toISOString()
  },

  // ==========================================
  // CHENNAI PROPERTIES
  // ==========================================
  {
    _id: "cp1",
    id: "cp1",
    title: "Premium 3 BHK Flat in OMR Chennai",
    description: "Luxury high-rise flat on OMR IT corridor, Chennai. Gated community with double lift, power backup, gym, and swimming pool. Close to top IT campuses.",
    listingType: "sale",
    price: 8500000,
    location: "OMR, Chennai",
    city: "Chennai",
    locality: "OMR",
    coordinates: { lat: 12.9719, lng: 80.2520 },
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 1550,
    area: "1550 sqft",
    category: "apartment",
    verified: true,
    featured: true,
    furnishing: "semi-furnished",
    parking: 1,
    amenities: ["Swimming Pool", "Gym", "Power Backup", "Security", "Lift"],
    reraId: "RERA-CHN-9080",
    advertiserType: "builder",
    createdAt: new Date().toISOString()
  },
  {
    _id: "cp2",
    id: "cp2",
    title: "2 BHK Flat for Rent in Velachery",
    description: "Beautiful semi-furnished 2 BHK flat for rent in Velachery. Very close to Phoenix Mall, supermarkets, and schools. Multi-vehicle parking.",
    listingType: "rent",
    price: 24000,
    location: "Velachery, Chennai",
    city: "Chennai",
    locality: "Velachery",
    coordinates: { lat: 12.9815, lng: 80.2230 },
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1100,
    area: "1100 sqft",
    category: "apartment",
    verified: true,
    featured: false,
    furnishing: "semi-furnished",
    parking: 1,
    amenities: ["Power Backup", "Security", "Parking"],
    advertiserType: "owner",
    createdAt: new Date().toISOString()
  },
  {
    _id: "cp3",
    id: "cp3",
    title: "Residential Land for Sale in Tambaram",
    description: "Premium CMDA approved layout residential land plot in Tambaram, Chennai. Gated community layout with blacktop roads and sweet ground water.",
    listingType: "sale",
    price: 3600000,
    location: "Tambaram, Chennai",
    city: "Chennai",
    locality: "Tambaram",
    coordinates: { lat: 12.9230, lng: 80.1170 },
    image: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 0,
    bathrooms: 0,
    areaSqft: 2000,
    area: "2000 sqft",
    category: "plot",
    verified: true,
    featured: true,
    furnishing: "unfurnished",
    parking: 0,
    amenities: ["Gated Boundary", "Rainwater Harvesting"],
    advertiserType: "dealer",
    createdAt: new Date().toISOString()
  },

  // ==========================================
  // MUMBAI PROPERTIES
  // ==========================================
  {
    _id: "mp1",
    id: "mp1",
    title: "Luxury 2 BHK Apartment in Powai",
    description: "Premium high-rise apartment flat in Hiranandani Powai. Stunning lake views, modern architectural details, modular wardrobes, and private parking slot.",
    listingType: "sale",
    price: 24000000,
    location: "Powai, Mumbai",
    city: "Mumbai",
    locality: "Powai",
    coordinates: { lat: 19.1176, lng: 72.9060 },
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 950,
    area: "950 sqft",
    category: "apartment",
    verified: true,
    featured: true,
    furnishing: "fully-furnished",
    parking: 1,
    amenities: ["Gym", "Swimming Pool", "Club House", "Power Backup", "Security"],
    reraId: "RERA-MUM-8910",
    advertiserType: "builder",
    createdAt: new Date().toISOString()
  },
  {
    _id: "mp2",
    id: "mp2",
    title: "Sea View 3 BHK Flat in Bandra West",
    description: "Stunning 3 BHK flat with unobstructed sea views in Bandra West. Extensively renovated with high-end marble flooring and Italian kitchen fittings.",
    listingType: "sale",
    price: 68000000,
    location: "Bandra, Mumbai",
    city: "Mumbai",
    locality: "Bandra",
    coordinates: { lat: 19.0544, lng: 72.8402 },
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 1450,
    area: "1450 sqft",
    category: "apartment",
    verified: true,
    featured: true,
    furnishing: "fully-furnished",
    parking: 2,
    amenities: ["Power Backup", "Security", "Parking", "Lift"],
    advertiserType: "owner",
    createdAt: new Date().toISOString()
  },

  // ==========================================
  // DELHI PROPERTIES
  // ==========================================
  {
    _id: "dp1",
    id: "dp1",
    title: "DDA Flat 3 BHK in Dwarka Sector 12",
    description: "Beautifully maintained DDA flat with 3 bedrooms, 2 bathrooms in Dwarka Sector 12. Gated society, green neighborhood, close to Sector 12 metro station.",
    listingType: "sale",
    price: 13500000,
    location: "Dwarka, Delhi",
    city: "Delhi",
    locality: "Dwarka",
    coordinates: { lat: 28.5920, lng: 77.0400 },
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 3,
    bathrooms: 2,
    areaSqft: 1450,
    area: "1450 sqft",
    category: "apartment",
    verified: true,
    featured: true,
    furnishing: "semi-furnished",
    parking: 1,
    amenities: ["Power Backup", "Security", "Parking", "Garden"],
    advertiserType: "owner",
    createdAt: new Date().toISOString()
  },
  {
    _id: "dp2",
    id: "dp2",
    title: "Luxury Builder Floor in Vasant Kunj",
    description: "3 BHK luxury independent builder floor with private lift and modern automation in Vasant Kunj. High-end finishes, modular wardrobes, and secure entry.",
    listingType: "sale",
    price: 26000000,
    location: "Vasant Kunj, Delhi",
    city: "Delhi",
    locality: "Vasant Kunj",
    coordinates: { lat: 28.5290, lng: 77.1620 },
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 3,
    bathrooms: 3,
    areaSqft: 1800,
    area: "1800 sqft",
    category: "builder-floor",
    verified: true,
    featured: true,
    furnishing: "semi-furnished",
    parking: 2,
    amenities: ["Lift", "Security", "Power Backup", "Parking"],
    advertiserType: "dealer",
    createdAt: new Date().toISOString()
  },

  // ==========================================
  // PUNE PROPERTIES
  // ==========================================
  {
    _id: "pp1",
    id: "pp1",
    title: "1 BHK Flat for Rent in Hinjewadi",
    description: "Perfect for IT professionals. Smart 1 BHK flat in a premium society close to Hinjewadi Phase 1 IT park. Fully loaded with clubhouse, gym, and 24/7 security.",
    listingType: "rent",
    price: 18000,
    location: "Hinjewadi, Pune",
    city: "Pune",
    locality: "Hinjewadi",
    coordinates: { lat: 18.5913, lng: 73.7389 },
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 1,
    bathrooms: 1,
    areaSqft: 650,
    area: "650 sqft",
    category: "apartment",
    verified: true,
    featured: false,
    furnishing: "semi-furnished",
    parking: 1,
    amenities: ["Power Backup", "Gym", "Security", "Parking", "Club House"],
    advertiserType: "dealer",
    createdAt: new Date().toISOString()
  },
  {
    _id: "pp2",
    id: "pp2",
    title: "Gated Luxury Villa in Baner Pune",
    description: "Premium 4 BHK independent villa in Baner. Spacious rooms with private deck, landscaped garden, private parking, and high-end security system.",
    listingType: "sale",
    price: 21000000,
    location: "Baner, Pune",
    city: "Pune",
    locality: "Baner",
    coordinates: { lat: 18.5590, lng: 73.7920 },
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1600&q=80",
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1600&q=80"],
    bedrooms: 4,
    bathrooms: 4,
    areaSqft: 3100,
    area: "3100 sqft",
    category: "villa",
    verified: true,
    featured: true,
    furnishing: "semi-furnished",
    parking: 2,
    amenities: ["Swimming Pool", "Gym", "Garden", "Security", "Power Backup"],
    reraId: "RERA-PUN-7766",
    advertiserType: "builder",
    createdAt: new Date().toISOString()
  }
];

export const MOCK_STATS = {
  Visakhapatnam: {
    city: "Visakhapatnam",
    listingType: "all",
    categoryCounts: [
      { _id: "apartment", count: 12 },
      { _id: "plot", count: 8 },
      { _id: "builder-floor", count: 6 },
      { _id: "villa", count: 4 },
      { _id: "office", count: 3 }
    ],
    bhkCounts: [
      { _id: 2, count: 8 },
      { _id: 3, count: 10 },
      { _id: 4, count: 4 }
    ],
    advertiserCounts: [
      { _id: "owner", count: 10 },
      { _id: "dealer", count: 15 },
      { _id: "builder", count: 5 }
    ]
  },
  Srikakulam: {
    city: "Srikakulam",
    listingType: "all",
    categoryCounts: [
      { _id: "independent-house", count: 9 },
      { _id: "plot", count: 15 },
      { _id: "apartment", count: 4 }
    ],
    bhkCounts: [
      { _id: 2, count: 5 },
      { _id: 3, count: 8 }
    ],
    advertiserCounts: [
      { _id: "owner", count: 12 },
      { _id: "dealer", count: 8 }
    ]
  },
  Hyderabad: {
    city: "Hyderabad",
    listingType: "all",
    categoryCounts: [
      { _id: "apartment", count: 15 },
      { _id: "independent-house", count: 12 },
      { _id: "plot", count: 10 }
    ],
    bhkCounts: [
      { _id: 2, count: 12 },
      { _id: 3, count: 18 }
    ],
    advertiserCounts: [
      { _id: "owner", count: 20 },
      { _id: "dealer", count: 15 }
    ]
  },
  Bangalore: {
    city: "Bangalore",
    listingType: "all",
    categoryCounts: [
      { _id: "apartment", count: 18 },
      { _id: "villa", count: 8 }
    ],
    bhkCounts: [
      { _id: 3, count: 15 },
      { _id: 4, count: 6 }
    ],
    advertiserCounts: [
      { _id: "owner", count: 14 },
      { _id: "dealer", count: 16 }
    ]
  },
  Chennai: {
    city: "Chennai",
    listingType: "all",
    categoryCounts: [
      { _id: "apartment", count: 14 },
      { _id: "plot", count: 9 }
    ],
    bhkCounts: [
      { _id: 2, count: 10 },
      { _id: 3, count: 8 }
    ],
    advertiserCounts: [
      { _id: "owner", count: 11 },
      { _id: "dealer", count: 9 }
    ]
  },
  Mumbai: {
    city: "Mumbai",
    listingType: "all",
    categoryCounts: [
      { _id: "apartment", count: 24 }
    ],
    bhkCounts: [
      { _id: 2, count: 15 },
      { _id: 3, count: 12 }
    ],
    advertiserCounts: [
      { _id: "owner", count: 18 },
      { _id: "dealer", count: 20 }
    ]
  },
  Delhi: {
    city: "Delhi",
    listingType: "all",
    categoryCounts: [
      { _id: "apartment", count: 19 },
      { _id: "builder-floor", count: 11 }
    ],
    bhkCounts: [
      { _id: 3, count: 14 }
    ],
    advertiserCounts: [
      { _id: "owner", count: 15 },
      { _id: "dealer", count: 15 }
    ]
  },
  Pune: {
    city: "Pune",
    listingType: "all",
    categoryCounts: [
      { _id: "apartment", count: 16 },
      { _id: "villa", count: 6 }
    ],
    bhkCounts: [
      { _id: 2, count: 10 }
    ],
    advertiserCounts: [
      { _id: "owner", count: 12 },
      { _id: "dealer", count: 10 }
    ]
  }
};
